version: '3.8'

services:
  dev-container:
    container_name: corsair
    build: .
    command: "sleep infinity"
    volumes:
      - ./source:/home/corsair/source
      - ./binaries:/home/corsair/binaries
      - ./examples:/home/corsair/examples
      - ./outputs:/home/corsair/outputs
      - ./tests:/home/corsair/tests
      - ./testsResults:/home/corsair/testsResults
      - ./Makefile:/home/corsair/Makefile
      - ./.clang-format:/home/corsair/.clang-format
    user: "${UID}:${GID}"
